on:
    pull_request:
      branches:
      # you can add more branches 
        - main
        - master
        - base
        - advanced
        - nobug
        - auth
        - mod
        - mode
        - starter
        - bug
    push:
      branches:
      # you can add more branches 
        - main
        - master
        - develop
        - base 
        - advanced
        - nobug
        - auth
        - mod
        - mode
        - starter
        - bug
  
name: "Build & Release"
jobs:
    build:
      permissions:
        contents: write
      name: Build & Release
      runs-on: windows-latest # macos-latest # ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v1
          with:
            java-version: '12.x' #  works fine for me Change That as Per Your Need If There is ANy Error in Future
          # with:
          #   java-version: '17.x'
            # you can change subosito/flutter-action@version as per your choice 
        - uses: subosito/flutter-action@v2
        #   with:
        # #   # you can change flutter-version: as per subosito/flutter-action@version as per your choice 
            # flutter-version: '3.0.0' #prefered with dart sdk 2.16.x
        #     channel: 'stable'
        # - run: flutter --version
        # - run: flutter doctor -v
        # - run: flutter pub get
        # - run: flutter pub global activate rename
        # - run: flutter pub global run rename -b we2gether.app.webview
        # - run: flutter pub global run rename --appname "We2gether"
        # - run: flutter pub run flutter_launcher_icons
        # - run: flutter gen-l10n
  
        # you can even build aab or ipa as per your command but remember you need to change the relese code for  artifacts:  directory
        # - run: flutter build apk --shrink --release --split-per-abi
        - name: Build 
          id: build
          uses: antinna/fa@v1.0.0
          with:
            # artifacts: "build/app/outputs/flutter-apk/*"
            # tag: v1.0.${{ github.run_number }}
            # PAT: ${{secrets.GITHUB_TOKEN}} 
            # gh_pages: true
            aab_generation: true
            apk_generation: true
            # ipa_generation: true
        # - name: Archive APK
        #   uses: actions/upload-artifact@v2
        #   with:
        #     name: debug-apk
        #     path: ${{ env.apk-path }}
        # - name: Archive AAB
        #   uses: actions/upload-artifact@v2
        #   with:
        #     name: debug-aab
            # path: ${{ env.aab-path }}       
